{{- if .Values.create_ogcapi_pod }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ogcapi.fullname" . }}
  annotations:
    geonetwork-hnap.version: {{ .Chart.Version }}
  labels:
{{ include "ogcapi.labels" . | indent 4 }}
spec:
  replicas:  {{ .Values.replicaCount }}
  selector:
    matchLabels:
      geonetwork-hnap/app: {{ include "ogcapi.name" . }}
      geonetwork-hnap/siteName: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        geonetwork-hnap/app: {{ include "ogcapi.name" . }}
        geonetwork-hnap/siteName: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GN_BASEURL
              value: {{ .Values.geonetworkweb.protocol }}://{{ .Values.geonetworkweb.url }}:{{ .Values.geonetworkweb.port }}/geonetwork/api
            - name: GN_INDEX_URL
              value: {{ .Values.elasticsearch.protocol }}://{{ .Values.elasticsearch.host }}:{{ .Values.elasticsearch.port }}
            - name: GN_LEGACY_URL
              value: {{ .Values.geonetworkweb.protocol }}://{{ .Values.geonetworkweb.url }}:{{ .Values.geonetworkweb.port }}/geonetwork/
            - name: JAVA_OPTS
              value: -Dfile.encoding=UTF-8
            - name: SERVER_FORWARDHEADERSSTRATEGY
              value: FRAMEWORK
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.dbname }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.postgres.dbuser }}
            - name: SPRING_PROFILES_ACTIVE
              value: standalone
          ports:
            - name: tcp
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

{{- end}}