{{- if .Values.create_postgis_pod }}
{{- $global := .Values.global | default dict }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgis.fullname" . }}-pvc
spec:
  accessModes:
  - {{ $global.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName: {{ $global.storageClassName | default .Values.pvc.storageClassName }}
{{- end}}