{{- if .Values.create_postgis_pod }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgis.fullname" . }}
  annotations:
    geonetwork-hnap.version: {{ .Chart.Version }}                           
  labels:
{{ include "postgis.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      geonetwork-hnap/app: {{ include "postgis.name" . }}
      geonetwork-hnap/siteName: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        geonetwork-hnap/app: {{ include "postgis.name" . }}
        geonetwork-hnap/siteName: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              value: {{.Values.postgres.dbuser}}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.dbname }}
          ports:
            - name: tcp
              containerPort: 5432
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/var/lib/postgresql"
              name: postgis-volume
            - name: init-postgres
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: postgis-volume
          persistentVolumeClaim:
            claimName: {{ include "postgis.fullname" . }}-pvc
        - name: init-postgres
          configMap:
            name: init-postgres-cm
            items:
            - key: init-sql
              path: init.sql

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end}}