{{- if .Values.create_elasticsearch_pod }}
{{- $global := .Values.global | default dict }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "elasticsearch.fullname" . }}-pvc
spec:
  accessModes:
  - {{ $global.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName: {{ $global.storageClassName | default .Values.pvc.storageClassName }}
{{- end}}