# Default values for kibana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

create_kibana_pod: true

replicaCount: 1

image:
  repository: kibana
  tag: 7.17.15
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "kibana"

service:
  type: ClusterIP
  port: 5601

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

elasticsearch:
  url: http://elasticsearch:9200/
  host: elasticsearch
  port: 9200