{{- if .Values.create_elasticsearch_pod }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  annotations:
    geonetwork-hnap.version: {{ .Chart.Version }}
  labels:
{{ include "elasticsearch.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: tcp
      port: {{ .Values.service.port }}
      targetPort: tcp
      protocol: TCP
  selector:
      geonetwork-hnap/app: {{ include "elasticsearch.name" . }}
      geonetwork-hnap/siteName: {{ .Release.Name }}

{{- end}}