{{- if .Values.create_postgis_pod }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    geonetwork-hnap/app: {{ include "postgis.name" . }}
  name: init-postgres-cm
data:
  init-sql: |-
    \c geonetwork
    CREATE SCHEMA geonetwork;
{{- end}}