# Default values for geonetwork-hnap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  #persistent volume claim
  pvc:
    # -- storageClass used by helm dependencies pvc
    storageClass: default
    # -- storage access mode used by helm dependency pvc
    accessMode: ReadWriteOnce
    # -- ReadWriteMany
    # -- Azure Disk is mounted as ReadWriteOnce, they're only available to a single node. 

#target k8s namespace
namespace: geonetwork

replicaCount: 1

image:
  repository: jingking/geonetwork-hnap
  #use "geonetwork" for standard geonetwork without HNAP plug-in
  tag: 4.2.7
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: &gn_host "geonetwork"
fullnameOverride: "geonetwork"

service:
  type: ClusterIP
  port: &gn_port 8080

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}


ingress:
  name: geonetwork-ingress
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/ingress.class: istio
  hosts:
    - host: geonetwork.example.com
      paths: [ "/geonetwork(.*)" ]

#database type
db_type: postgres

postgres:
  host: &db_host geonetwork-db
  port: &db_port 5432
  dbuser: &db_user geonetwork
  password: &db_password geonetwork
  dbname: &db_name geonetwork

elasticsearch:
  host: &es_host elasticsearch
  port: &es_port 9200
  protocol: http
  # values override for subchart elasticsearch
  create_elasticsearch_pod: true
  nameOverride: *es_host
  service:
    port: *es_port
  pvc:
    # initial size for index storage
    size: 100Mi

kibana:
  host: &kb_host kibana
  port: &kb_port 5601
  # values override for subchart kibana
  create_kibana_pod: true
  nameOverride: *kb_host
  service:
    port: *kb_port
  elasticsearch:
    host: *es_host
    port: *es_port

ogcapi:
  host: &oa_host ogcapi
  port: &oa_port 8080
  # values override for subchart ogc api record service
  create_ogcapi_pod: true
  nameOverride: *oa_host
  service:
    port: *oa_port

  elasticsearch:
    host: *es_host
    port: *es_port

  geonetworkweb:
    host: *gn_host
    port: *gn_port

  postgres:
    host: *db_host
    port: *db_port
    dbuser: *db_user
    password: *db_password
    dbname: *db_name

pvc:
  # initial size for geonetwork catalogue data
  size: 1Gi
  # storage Class
  storageClassName: local-storage


# values override for subchart postgis
postgis:
  create_postgis_pod: true
  nameOverride: *db_host
  postgres:
    port: *db_port
    dbuser: *db_user
    password: *db_password
    dbname: *db_name
  pvc:
    # initial size for pgsql disk
    size: 1Gi